/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wecare;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import static java.sql.DriverManager.getConnection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Fariha
 */
public class Coachs extends javax.swing.JFrame {

   
    /** Creates new form Coachs */
    public Coachs() {
        initComponents();
        DisplayCoachs();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CNameTb = new javax.swing.JTextField();
        CPhoneTb = new javax.swing.JTextField();
        CAgeTb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CAddTb = new javax.swing.JTextField();
        CGenCb = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        EditBtn = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CoachTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payments");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 210, 140, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Logout");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 290, 105, 39);

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Members");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 120, 130, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-10, 0, 280, 600);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Coach Lists");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 400, 446, 29);

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel5.setText("Phone Number ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 150, 182, 39);

        jLabel6.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel6.setText("Coach Name ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 100, 170, 39);

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel7.setText("Age");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 280, 110, 30);
        jPanel1.add(CNameTb);
        CNameTb.setBounds(500, 100, 159, 26);

        CPhoneTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPhoneTbActionPerformed(evt);
            }
        });
        jPanel1.add(CPhoneTb);
        CPhoneTb.setBounds(490, 150, 160, 26);
        jPanel1.add(CAgeTb);
        CAgeTb.setBounds(390, 280, 100, 26);

        jLabel8.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel8.setText("Address");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(290, 210, 159, 39);
        jPanel1.add(CAddTb);
        CAddTb.setBounds(490, 220, 159, 26);

        CGenCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(CGenCb);
        CGenCb.setBounds(650, 280, 81, 26);

        jLabel11.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel11.setText("Gender");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(530, 270, 81, 39);

        EditBtn.setBackground(new java.awt.Color(102, 0, 102));
        EditBtn.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditBtn.setText("EDIT");
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
        });
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        jPanel1.add(EditBtn);
        EditBtn.setBounds(290, 340, 117, 30);

        AddBtn.setBackground(new java.awt.Color(102, 0, 102));
        AddBtn.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddBtn.setText("ADD");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AddBtn);
        AddBtn.setBounds(450, 340, 117, 30);

        DeleteBtn.setBackground(new java.awt.Color(102, 0, 102));
        DeleteBtn.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("DELETE");
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });
        jPanel1.add(DeleteBtn);
        DeleteBtn.setBounds(610, 340, 150, 30);

        jLabel12.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel12.setText("Manage Trainers");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(500, 20, 446, 59);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 0, 730, 450);

        CoachTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CoachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CoachTable.setRowHeight(28);
        CoachTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoachTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CoachTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(270, 450, 730, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1289, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CPhoneTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPhoneTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPhoneTbActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditBtnActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new Members().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new Payments().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked
  Connection Con=null;
PreparedStatement pst =null;
ResultSet Rs=null, Rs1=null;
Statement St=null,St1=null;
private void DisplayCoachs()
{
    try{
        Con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/gymdb","root","");
        St=(Statement) Con.createStatement();
        Rs=St.executeQuery("select * from coachtbl");
        CoachTable.setModel(DbUtils.resultSetToTableModel(Rs));
    }catch(Exception e){
        
    }
}
    int CNum=0;
    private void CountCoach()
    {
        try{
            St1=(Statement) Con.createStatement();
            Rs1= St1.executeQuery("select Max(CId) from coachtbl");
            Rs1.next();
            CNum=Rs1.getInt(1)+1;
        }catch(Exception e){
            
        }
    }
    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        // TODO add your handling code here:
        if(CNameTb.getText().isEmpty()||CPhoneTb.getText().isEmpty()||CAgeTb.getText().isEmpty()||CAddTb.getText().isEmpty()||CGenCb.getSelectedItem()=="")
        {
          JOptionPane.showMessageDialog(this,"Missing Information");
        }else
        {
            try{
                CountCoach();
             Con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/gymdb","root","");
             PreparedStatement Add = (PreparedStatement) Con.prepareStatement("insert into coachtbl values(?,?,?,?,?,?)");
             Add.setInt(1, CNum);
             Add.setString(2, CNameTb.getText());
             Add.setString(3, CPhoneTb.getText());
             Add.setInt(4, Integer.valueOf(CAgeTb.getText()));
             Add.setString(5, CAddTb.getText());
             Add.setString(6, CGenCb.getSelectedItem().toString());
             int row = Add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Trainer Saved");
            Con.close();
             DisplayCoachs();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
        
    }//GEN-LAST:event_AddBtnMouseClicked
    int Key=0;
    private void CoachTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoachTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)CoachTable.getModel();
        int MyIndex = CoachTable.getSelectedRow();
        Key = Integer.valueOf(model.getValueAt(MyIndex, 0).toString());
        CNameTb.setText(model.getValueAt(MyIndex, 1).toString()); 
        CPhoneTb.setText(model.getValueAt(MyIndex, 2).toString()); 
        CAgeTb.setText(model.getValueAt(MyIndex, 3).toString()); 
        CAddTb.setText(model.getValueAt(MyIndex, 4).toString()); 
        CGenCb.setSelectedItem(model.getValueAt(MyIndex, 5).toString());
        
                
    }//GEN-LAST:event_CoachTableMouseClicked

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        // TODO add your handling code here:
        if(Key==0){
            JOptionPane.showMessageDialog(this, "Select the coach to delete");
            
        }
        else{
            try {
                Con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/gymdb","root","");
                String Query = "Delete from CoachTbl where CId="+Key;
                Statement Del=(Statement) Con.createStatement();
                Del.executeUpdate(Query);
                JOptionPane.showMessageDialog(this, "Coach Deleted");
                DisplayCoachs();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
            
        }
    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        // TODO add your handling code here:
        if(Key==0){
                JOptionPane.showMessageDialog(this, "Select The Coach to Edit");

        }else{
            try {
                Con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/gymdb","root","");
                String Query="Update CoachTbl set CName=?,Cphone=?,CAge=?,CAddress=?,CGen=? where CId=?";
                PreparedStatement Edit=(PreparedStatement) Con.prepareStatement(Query);
                Edit.setString(1, CNameTb.getText());
                Edit.setString(2, CPhoneTb.getText());
                Edit.setInt(3, Integer.valueOf(CAgeTb.getText()));
                Edit.setString(4, CAddTb.getText());
                Edit.setString(5, CGenCb.getSelectedItem().toString());
                Edit.setInt(6, Key);
                int row = Edit.executeUpdate();
            JOptionPane.showMessageDialog(this, "Trainer Updated");
            Con.close();
             DisplayCoachs();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_EditBtnMouseClicked

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coachs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coachs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coachs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coachs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coachs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField CAddTb;
    private javax.swing.JTextField CAgeTb;
    private javax.swing.JComboBox<String> CGenCb;
    private javax.swing.JTextField CNameTb;
    private javax.swing.JTextField CPhoneTb;
    private javax.swing.JTable CoachTable;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   

}
