/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wecare;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fariha
 */
public class Diet extends javax.swing.JFrame {

    /**
     * Creates new form Diet
     */
    public Diet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel2.setText("WELCOME TO THE DIET PLAN PAGE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 20, 710, 50);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel3.setText("ENTER  BMI");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 80, 160, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(490, 80, 100, 26);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Foods you should eat", "Time", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 360, 750, 140);

        jButton3.setBackground(new java.awt.Color(102, 0, 102));
        jButton3.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Click to generate diet plan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 180, 430, 40);

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel4.setText("ENTER  NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 130, 190, 30);

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("HomePage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 307, 170, 40);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(490, 130, 100, 26);

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLICK TO SEE DIET PLAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 240, 430, 47);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/319287458_1319918292099033_6968288201091019061_n.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 0, 760, 500);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel8.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BMI");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Calorie Counter");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("WorkoutPlan");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Logout");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel10)))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(94, 94, 94))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addComponent(jLabel11)
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 500);

        setSize(new java.awt.Dimension(1022, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int iBMI=Integer.parseInt(jTextField1.getText());
        
        Object row1[] = {"milk/nuts/red meats", "morning/snacks/dinner", "as much as you want"};
        Object row2[] = {"roti/dal/oats", "lunch/dinner/breakfast", "1/1 cup/1 bowl"};
        //Object row3[] = {"", "7", "15 min"};
        //Object row4[] = {"Jumping Rope", "7", "10 min"};
       // Object row5[] = {"Walking", "7", "60 min"};
        Object row3[] = {"Tea with less sugar and milk", "morning", "1 teacup"};
        Object row4[] = {"Mixed Vegetable Salad", "lunch/dinner", "1 plate"};
        Object row5[] = {"Fresh Fruit:apple,orange,banana,guava", "after lunch/after dinner", "1 piece each "};

        DefaultTableModel dt =(DefaultTableModel)jTable1.getModel();
        dt.setRowCount(0);
        ArrayList<String> o=new ArrayList(Arrays.asList("Workout you should try", "Weekly how many days", "Duration of workout"));
        dt.setColumnCount(o.size());
        
        for(int j=0; j<3; j++)
            jTable1.getColumnModel().getColumn(j).setHeaderValue(o.get(j));
        
        if( iBMI<=24.9)
        {
            dt.addRow(row1);
        }
        else if(iBMI <=29.9)
        {
            dt.addRow(row2);
        }
        else if(iBMI <=34.9)
        {
            dt.addRow(row3);
        }
        else if(iBMI <=39.9)
        {
            dt.addRow(row4);
        }
        else if(iBMI >=40)
        {
            dt.addRow(row5);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Physical().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        setVisible(false);
            new BMI().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        setVisible(false);
            new Calorie().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        setVisible(false);
            new Workout().setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name=jTextField2.getText();
        String bmi=jTextField1.getText();
        String path="D:\\";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc,new FileOutputStream(path+""+name+".pdf"));
              doc.open();
            Paragraph paragrgraph1=new Paragraph("                                         WeCare\n");
            doc.add(paragrgraph1);
             Paragraph paragrgraph2=new Paragraph("*********************************************************************************");
            doc.add(paragrgraph2);
            Paragraph paragrgraph3=new Paragraph("\tCustomer Details:\nName: "+name+"\nBMI: "+bmi+"\n");
            doc.add(paragrgraph3);
            doc.add(paragrgraph2);
            //Paragraph paragrgraph4=new Paragraph("\tRoom Details:\nNumber:"+jTextField1.getText()+"\nType: "+roomType+"\nBed: "+bed+"\nPrice per Day: "+jTextField6.getText()+"");
            // doc.add(paragrgraph4);
             doc.add(paragrgraph2);
             PdfPTable tb1=new PdfPTable(4);
             tb1.addCell("NAME: "+jTextField2.getText()+"\n");
             tb1.addCell("BMI: "+bmi+"\n");
            int iBMI=Integer.parseInt(jTextField1.getText()); 
             if( iBMI<=24.9)
        {
            //dt.addRow(row1);
             tb1.addCell("Foods you should eat: milk/nuts/red meats \n");
             tb1.addCell("Time: morning/snacks/dinner \n");
             tb1.addCell("Quantity: as much as you want \n");
            
        }
        else if(iBMI <=29.9)
        {
            //dt.addRow(row2);
             tb1.addCell("Foods you should eat: roti/dal/oats \n");
             tb1.addCell("Time: lunch/dinner/breakfast \n");
             tb1.addCell("Quantity: 1/1 cup/1 bowl \n");
        }
        else if(iBMI <=34.9)
        {
            //dt.addRow(row3);
             tb1.addCell("Foods you should eat: Tea with less sugar and milk \n");
             tb1.addCell("Time: morning/snacks/dinner \n");
             tb1.addCell("Quantity: 1 teacup \n");
        }
        else if(iBMI <=39.9)
        {
            //dt.addRow(row4);
             tb1.addCell("Foods you should eat: Mixed Vegetable Salad \n");
             tb1.addCell("Time: lunch/dinner \n");
             tb1.addCell("Quantity: 1 plate \n");
        }
        else if(iBMI >=40)
        {
           // dt.addRow(row5);
             tb1.addCell("Foods you should eat: Fresh Fruit:apple,orange,banana,guava \n");
             tb1.addCell("Time: after lunch/after dinner \n");
             tb1.addCell("Quantity: 1 piece each \n");
        }
             //tb1.addCell("DietPlan: "+type+"");
             //tb1.addCell("Total Amount Paid: "+totalAmount+"");
             doc.add(tb1);
             doc.add(paragrgraph2);
             Paragraph paragrgraph5=new Paragraph("Thank you ,Please visit Again.");
             doc.add(paragrgraph5);
                          
                         
                   
                   
                
             
            
          
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        int a=JOptionPane.showConfirmDialog(null,"Do you want to print the diet plan ?","Selecyt",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            try{
                if((new File("D:\\"+name+".pdf")).exists())
                {
                    Process p=Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler D:\\"+name+".pdf");
                }
                else
                    System.out.println("File is not Exists");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
